### ISSUE TITLE
git <TAB> doesn't complete Git aliases with ZSH

### ISSUE THREAD

**Issue by gpakosz** [felipec/git-completion#7]
Hello,

I added a Git alias with
```
$ git config --global alias.foo '!echo foo'
```

However, typing `git` followed by `<TAB>` only prints out what's defined in `__git_zsh_cmd_common()`.
Is there a way to make Git aliases completion work?

Alternatively, is there a way to add a custom completion for `git foo` when `git-foo()` is a custom command of mine that doesn't come with upstream Git?

**Comment by felipec** [comment]
Aliases are completed, but they are typically not shown if a common command is found first. You can use zstyle to configure zsh's completion system to show aliases too by default:

    zstyle ':completion:*:*:git:*' tag-order 'common-commands,alias-commands'

**Comment by gpakosz** [comment]
Ah nice!

And your version doesn't offer `user-commands` like upstream ZSH or Git's bash completion do?

**Comment by felipec** [comment]
The git's zsh completion is a wrapper around git's bash completion, so if it's supported by git's bash completion, it should be supported by git's zsh completion too.

I suppose by "user command" you mean something like a user completion, like:

    _git_foo () { _git_log; }

If so, that should work in zsh as well.

**Comment by gpakosz** [comment]
So yeah completing `git foo` works after having defined `_git_foo()`, but typing `git` then `<TAB>` doesn't list the `foo` command that comes from outside of Git.

Not sure if there's a way around that.

**Comment by felipec** [comment]
Didn't you just say `zstyle` does list the `foo` alias? Is it an alias or is it a `git-foo` binary? If it's a separate command you need `all-commands` instead of `common-commands`.

Or just list everything:

    zstyle ':completion:*:*:git:*' tag-order 'common-commands,all-commands,alias-commands'

**Comment by gpakosz** [comment]
Thanks for mentioning `all-commands`.

**Comment by gpakosz** [comment]
So yeah I didn't realize using `common-commands,all-commands,alias-commands` would aggregate the 3 outputs.
I somewhat expected a way to display the same thing as `common-commands` but with my "user command" injected into the list 🙂

**Comment by felipec** [comment]
The are proposals on how to improve the list of commands for the completions, but none have materialized.

For now I just listed the common commands and added the descriptions myself manually.

All the commands are completed anyways, even your `git-foo` custom command, but they are not initially listed by default.

You can also show the [group names](https://stackoverflow.com/questions/16240729/zsh-show-completion-group-names) if you want to differentiate common commands from all commands and so on.

I'm not sure we can do much more at this point. So I guess this issue is resolved.
